### ISSUE TITLE
Issue with available ciphers

### ISSUE THREAD

**Issue by cmoberg** [Juniper/go-netconf#1]
I'm trying to get the go-netconf library working with our implementation of NETCONF in the Tail-f ConfD product.

```
calle@macbook:calle-src $go run netconf.go
panic: handshake failed: ssh: no common algorithms

goroutine 1 [running]:
main.main()
    /Users/calle/calle-src/netconf.go:32 +0x17f

goroutine 2 [syscall]:
exit status 2
```

Is there a way for me to trace the handshake from the client side to see which ciphers are being suggested?

**Comment by nemith** [comment]
Looks to be fixed via #22
