### ISSUE TITLE
Netconf call home support

### ISSUE THREAD

**Issue by GiacomoCortesi** [Juniper/go-netconf#105]
Hi guys,

I'd like to understand what's your plan for expanding this library and adding missing NETCONF client functionalities.
Is this library still actively maintained? Do you accept external contributions at this time?

In particular I see that there is no support for netconf call home procedure yet (rfc8071) and other netconf operations defined in rfc6241.
Any development plan in action for the future?

Thank you!

**Comment by nemith** [comment]
Workin on a v2 rewrite (tracking in #24).  Call home support is planned but may be later to make sure the core api is correct.

**Comment by GiacomoCortesi** [comment]
I’m glad to hear that you’re planning a rewrite. I have a fork where I added some functionalities such as callhome, notifications support, chunked framing and netconf operations. I’m actively using the library and I’d be interested in discussing/participating the rewrite if you are willing to accept external contributions.

**Comment by nemith** [comment]
Contributions would be very very welcome.  Even to bounce design ideas off of (or API) before it become "locked in"

My very early version can be found here https://github.com/nemith/go-netconf/blob/v2/transport/frame.go#L100.

**Comment by GiacomoCortesi** [comment]
I've checked out the new draft code for v2 and I like the setup.
I'd like to help out with callhome and netconf operations, they are already implemented in my fork (but I think there is room for improvement) so maybe I can fill a design proposal and start from there.

Anyway, I'll dive deeper in the next days and let you know what comes to my mind!
