### ISSUE TITLE
panic: ssh: subsystem request failed

### ISSUE THREAD

**Issue by tobor** [Juniper/go-netconf#12]
golang.org/x/crypto/ssh
Does not support Juniper ScreenOS

**Comment by dssatya** [comment]
Thanks tabor. Will look into it.

**Comment by nemith** [comment]
Subsystem request failed would usually mean that it cannot start the netconf subsystem.  I am not sure this is a golang.org/x/crypto/ssh thing.

**Comment by nemith** [comment]
You can test connecting up the subsystem with 'ssh <hostname> -s netconf".  I am not sure if screenos uses a seperate port for netconf like Junos does but make sure to include that as well 'ssh <hostname> -s netconf -p 830'

**Comment by nemith** [comment]
Closing since there has been no response in a long time.  If someone can recreate the problem, please reopen and/or drop me a message.
