### ISSUE TITLE
Telnet connection waits forever

### ISSUE THREAD

**Issue by dakshinai** [Juniper/go-netconf#31]
I'm testing the example program telnet_example.go from a window machine. I'm able to telnet from the windows telnet client to a ubuntu machine (on network) running telnet server. However when I run the example program for the same ubuntu host using credentials, the programs waits on vendor.Login(t, username, password) forever. I believe it is expecting some regex match in this step _, prompt, err := t.WaitForRegexp(promptRE) in jnpr/ioproc.go forever. 

Any suggestions as to what could be wrong and how it can be fixed?

**Comment by nemith** [comment]
What junos device are you connecting to?  In general the telnet logic is a hack and not really officially supported NETCONF transport.
