### ISSUE TITLE
Need help to programatically construct edit-config request

### ISSUE THREAD

**Issue by mjoshiNetElastic** [Juniper/go-netconf#35]
I am trying to programatically construct netconf edit-config request for a yang schema config object. Currently I am constructing this xml string manually. Is there a way I can do this programatically given the yang schema file? Please help

**Comment by nemith** [comment]
Not as part of this library.  You can use `encoding/xml` from Go to create the xml object or possibly use a yang library that can serialize to xml.   Either is out of the scope of this project
