### ISSUE TITLE
Add support for <xnm:error /> management protocol operational errors

### ISSUE THREAD

**Issue by charl** [Juniper/go-netconf#6]
I get the following response (from a srx that does not currently have a cx111 attached to one of the USB ports):

``` xml
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/11.4R9/junos" message-id="8fe866c66684646c42df2beace371f37">
  <xnm:error xmlns="http://xml.juniper.net/xnm/1.1/xnm" xmlns:xnm="http://xml.juniper.net/xnm/1.1/xnm">
    <source-daemon>wireless-wan-service</source-daemon>
    <message>Adapter is not present.</message>
  </xnm:error>
</rpc-
```

**Comment by nemith** [comment]
I think we should try to solve this with an Extra field on the RPC Reply that uses `,any` in encoding/xml

> * If the XML element has an attribute not handled by the previous
>   rule and the struct has a field with an associated tag containing
>   ",any,attr", Unmarshal records the attribute value in the first
>   such field.

**Comment by nemith** [comment]
Actually I am closing this.  It's in violation of the RFC and we have RawReply in the struct to allow you to parse the error directly.
