### ISSUE TITLE
DialSSH not closing SSH session when netconf fails.

### ISSUE THREAD

**Issue by bsherwood12** [Juniper/go-netconf#86]
DialSSH (https://github.com/Juniper/go-netconf/blob/master/netconf/transport_ssh.go#L111)
Does not close the ssh session if the netconf session fails.

DialSSH needs to close the ssh session if the netconf session fails, or handle this situation in some way that does not cause a hung ssh session.

**Comment by pplavetzki** [comment]
@bsherwood12 I will create a pull request referencing this issue.
