### ISSUE TITLE
Getting segfault for DialSSH call when incorrect ssh username/password provided.

### ISSUE THREAD

**Issue by paulsubrata55** [Juniper/go-netconf#90]
* What is the issue
Getting segfault for DialSSH call when incorrect ssh username/password provided. This is caused due to PR #87. The TransportSSH.Dial failure may happen due to many reasons, one of them is incorrect username/password. In this scenario there is no valid ssh connection to close.
* What is expected
netconf client must not crash for incorrect ssh username/password.
* How it can be solved (suggestion)
Detect there is a valid ssh connection before closing one.

**Comment by paulsubrata55** [comment]
stack trace below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5930c3]

goroutine 1 [running]:
github.com/Juniper/go-netconf/netconf.(*TransportSSH).Close(0xc00008abc0, 0x5fca8d, 0xe)
	/home/user/Practice/gopath/src/github.com/Juniper/go-netconf/netconf/transport_ssh.go:49 +0x33
github.com/Juniper/go-netconf/netconf.DialSSH(0x5fca8d, 0xe, 0xc000042ec0, 0xc00008ab80, 0x634ba0, 0xb)
	/home/user/Practice/gopath/src/github.com/Juniper/go-netconf/netconf/transport_ssh.go:115 +0x89
main.main()
	/home/user/Practice/netconf-go/main.go:22 +0x17f

```

**Comment by kpostrup** [comment]
If no one has any objections to this, can it please be merged?
I've tested it locally and it solves the problem for me.
