### ISSUE TITLE
ssh: handshake failed: EOF

### ISSUE THREAD

**Issue by marzdgzmn** [Juniper/go-netconf#93]
I tried both ssh1 and ssh2 examples but I'm getting an error:
`ssh: handshake failed: EOF`

**Operating System:** _CentOS7_
**Go Version:** _go1.13.11 linux/amd64
**Go Env:**_
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/go-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build171988649=/tmp/go-build -gno-record-gcc-switches"
```

If it helps, I'm using Python's PyEZ framework/library on the same machine and it works just fine.

**Comment by ngadre-juniper** [comment]
Hi, Is there any connection limit on the box, can you share the ssh related configuration also on the router.

**Comment by ngadre-juniper** [comment]
@marzdgzmn check for the cipher deprecation issue of the ssh package used in this package

**Comment by nemith** [comment]
ssh: handshake failed: EOF  means you have a ssh error. This is usually auth or cyphers.  This is before this library takes over so try to troublshoot with just ssh first.
